### ISSUE TITLE
compete mode AI progress bar is too fast

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/mobvita#107]
should mobile get a slower bar? using mobile is much slower than keyboard

**Comment by saparagus** [comment]
In both interfaces (Mobile or Desk): BackEnd **has a model** of how user behaved previously (or **default** model) -- this model is used to pace the opponent's progress and rate of correct answers.

biggest problem here seems to be: current MobVita opponent bar is for the **current snippet** -- original DeskVita opponent bar is for **entire story**.  Currently, the latter seems to make more sense

For details: please see competition JS code in old Revita or ask @hj940709 or anyone on   Revita team

**Comment by Granigan** [comment]
Will the backend model differentiate whether I'm on mobile or desktop? Meaning what happens when I use Mobvita on both; will speed bar adjust to average, possibly making it too slow for desktop and too fast on mobile?

**Comment by hj940709** [comment]
@Granigan No, the backend does not differentiate.
