### ISSUE TITLE
Design side bar functions and layout

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/mobvita#112]

**Comment by saparagus** [comment]
current animation design is good.  
We suppose that this is **always** present on all views ?
Functions to provide -- initially model on DeskVita's old menubar: buttons in this order - from top-to-bottom:
- Home: to home page
- Stories: ??? keep this?  maybe ok, to go to story list of last selected learning language
- Tour: to future Tour
- Help: to future HELP page
- About: to future "About Project" page
- Contact: future simple interface to contact us
- horizontal bar / separator ---------------------------------
- Interface language selector
- **Settings**: important --> to Settings page
- Logout: (last option)
