### ISSUE TITLE
Make multiplechoice look better

### ISSUE THREAD

**Issue by markokoskinen2037** [UniversityOfHelsinkiCS/mobvita#120]
Currently it's not perfect, make it better

**Comment by saparagus** [comment]
Two improvements needed:
- height of box should be smaller -- takes too much space **especially** on Mobile
- inside menu, the selected option should **not** be repeated, as it is now.  Each option visible only once.  If we want to allow the user to **deselect** all options, we can have a blank option (in DeskVita this option is the string "_____" -- probably not the best solution).
But seeing the selected option appearing **twice** is a worse design.
