### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by saparagus** [UniversityOfHelsinkiCS/mobvita#610]
- [ ] **Learning settings**
  - FIN, RUS: concept names missing
- [x] **Learning language**
  - FIN: tatar ⇒Tataari, kazakh ⇒kazakki, udmurt ⇒udmurtti
  - RUS: tatar ⇒ Татарский
- [x] **Practice Now** view
  - FIN, RUS: "Start random story from N stories"

**Comment by Granigan** [comment]
separating
"Learning settings
FIN, RUS: concept names missing"
to its own issue
