### ISSUE TITLE
Make text in exercise flow better

### ISSUE THREAD

**Issue by markokoskinen2037** [UniversityOfHelsinkiCS/mobvita#70]
Make span and exercise element flow like a page in a research document would, so that the right edge of whole exercise is clean.

**Comment by saparagus** [comment]
not sure that adjusting right side is essential.
On the other hand -- working out the **width** of the textboxes is essential.  Currently most are too long (in FI, for example), and some are too short.
We (REVITA team) have two algorithms / approaches for solving this problem - let's choose one
