### ISSUE TITLE
UI: figure out proper colors for exercises

### ISSUE THREAD

**Issue by esakemp** [UniversityOfHelsinkiCS/mobvita#72]
currently just randomly picked colors because I know nothing about UI design

-Let's agree on a palette. -tt

**Comment by saparagus** [comment]
Let's use DeskVita as the model initially -- this will change a bit soon.  Suggestion:
Initially:
- cloze exercise: color = light yellow, no border
- multi-choice exercises: color = light yellow (OK), border as all menus
- listening exercises: color = light yellow, clearly visible speaker icon in middle
after first attempt:
- exercises done correctly: color = light green (not modifiable / frozen, cursor turns to "thumb up") 
- exercises done wrong: color = light red/orange, POSSIBLY hints appear on mouseover (depending on exercise)
- exercises done "partially wrong": color = light blue, hints appear on mouseover
final feedback: after all attempts: (feedback appears on mouseover / tooltips)
- done correctly: color = light green
- done wrong: color = light red/orange
- done partially wrong: color = light blue
