### ISSUE TITLE
Progress table in profile page: fix min and max

### ISSUE THREAD

**Issue by ilmarikyl** [UniversityOfHelsinkiCS/mobvita#957]
*** Individual student's **OWN progress view**: define the time period in CALENDAR widget:

- CURRENTLY: max = present moment, min = 2 months ago
- NEW: when entering Progress view - select a "sensible" **default** time period 
  - MAX: last day + 1 when student DID PRACTICE (possibly tomorrow: now+1)
  - MIN: *the LATER one* of these two dates: 
    - month of FIRST practice
    - 6 months before max

- LATER: POSSIBLY, if the view does not look good:
  - MAX - (round off to end of month)
  - MIN - (round off to beginning of month)

**Comment by saparagus** [comment]
in GROUP Summary view: set the time period: 
- MAX: latest date over all students
- MIN: earliest date over all students
