### ISSUE TITLE
Updates to difficulty settings

### ISSUE THREAD

**Issue by nettivastaava** [UniversityOfHelsinkiCS/mobvita#977]
- [x] 1. Ask user's CEFR level in **Settings** view (as a slider)
- [x] 2. Show the CEFR slider after **REGISTRATION**: (make box bigger)
   - For students who have not checked off their level: upon next login POPUP "Select your CEFR level"
   - after registration
   - different popup - in addition to or instead of usual WELCOME popup 
- [x] 3. HIGHLIGHT the **BACKGROUND** of words in these modes:
  - PREVIEW
  - PRACTICE
  - (?REVIEW)
- add background color = (MAX difficulty of concepts attached to word ) - Student's level
  - 0 = white
  - `< 0` = greener
  - `> 0` = redder

**Comment by saparagus** [comment]
- TASK 4: computation of BACKGROUND COLOR is done like this: GIVEN the values
  - U = user's current level (0-12, but really 2-9)
  - C = candidates difficulty (0-12)
  - R = strongest red color suitable for use as background highlighting
  - G = strongest green color suitable for use as background highlighting
  - W = white (#FFFFFF)

- compute background color B as:
  - D = U - C  --- difference
  - if  | D | <= 1  ⇒   B = white  --- for 1 point above or below U ⇒ background is white.
  - else: if U < C:  D is linear interpolation between: W for U+1, and R for U+7
  - else: if U > C:  D is linear interpolation between: W for U-1, and G for U-7

**Comment by saparagus** [comment]
## Highlight colors in preview + review + practice modes

### default toggle settings

- NOW default REVIEW off for student, default on for teacher
- _add chosen SETTINGS to **USER object**

____________________________________________________________________________
### PREVIEW mode:

- EXERCISE toggle only
  - controls underlining + circles
  - _controls ALSO difficulty highlight_

(no separate DIFFICULTY toggle)

____________________________________________________________________________ 
### REVIEW mode: 

- always show feedback, **remove toggle for feedback**
- **add toggle difficulty highlight**

__________________________
### PRACTICE mode:
**history snippets**

- exactly as REVIEW mode
  - add same difficulty toggle as we have in REVIEW mode

**current snippet**

- all exercise boxes - difficulty highlight (as now)
- colors always SHOWN (? might change later if users don't like it)
- (difficulty toggle does not affect anything)
